### PR TITLE
fix: rp-adapter validation of VP proofs

### LINKED ISSUE #191: [Issuer Adapter] Validate VP sent in Present Proof

### PR DESCRIPTION
**Pull request by llorllale**
part of #145 
closes #191

**Summary**

Tested against sandbox commit `d20654eb9d7612d620f4ee2f61dec83ebe50d0d0`.

The RP Adapter is now signing the VP enclosing the authZ credential with the tenant's DID before presenting it to the Issuer Adapter. The Issuer Adapter is now verifying the proof on this VP.

The aries framework's `verifiable.ParsePresentation()` was fixed to verify the embedded proofs in presentations: hyperledger/aries-framework-go#2049.

Upgrading to the newest version exposed lots of bugs and assumptions around the validation of proofs in VPs and VCs which have been addressed in this patch, either as full fixes or followup action items.

Signed-off-by: George Aristy <george.aristy@securekey.com>

### CODE REVIEW

File: pkg/vc/issuer/credentials.go [hunk 1]
```diff
@@ -71,7 +71,7 @@ func CreateManifestCredential(issuerName string, supportedContexts []string) ([]
 // ParseWalletResponse parses VP received from the wallet and returns the DIDConnect response.
 func ParseWalletResponse(vpBytes []byte) (*DIDConnectCredentialSubject, error) {
 	// TODO https://github.com/trustbloc/edge-adapter/issues/87 validate the signature
-	pres, err := verifiable.ParsePresentation(vpBytes, verifiable.WithDisabledPresentationProofCheck())
+	pres, err := verifiable.ParsePresentation(vpBytes, verifiable.WithPresDisabledProofCheck())
```
Comment (llorllale) [inline pkg/vc/issuer/credentials.go:74]: uhm - I may have missed this

Comment (llorllale) [reply pkg/vc/issuer/credentials.go:74]: should be done in a followup PR (ie. the issue referenced in the TODO) as this involves verifying the proof in the VP the wallet delivers to the issuer adapter.

Comment (llorllale) [reply pkg/vc/issuer/credentials.go:74]: This PR is all about the RP Adapter signing the verifiable presentation enclosing the authZ VC that is sent to the Issuer Adapter as proof they have been authorized to access the resource.
